apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movies-app
  template:
    metadata:
      labels:
        app: movies-app
    spec:
      containers:
      - name: movies-app
        image: dhash23/movies-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: MONGO_URI_TEMPLATE
        volumeMounts:
        - name: mongodb-credentials
          mountPath: /etc/mongodb-credentials
          readOnly: true
        - name: mongodb-config
          mountPath: /etc/mongodb-config
          readOnly: true
      volumes:
      - name: mongodb-credentials
        secret:
          secretName: mongodb-credentials
      - name: mongodb-config
        configMap:
          name: mongodb-config
