apiVersion: v1
kind: Service
metadata:
  name: movies-app-service
spec:
  selector:
    app: movies-app
  ports:
  - protocol: TCP
    port: 8080  # External port
    targetPort: 3000  # Port the application listens on
  type: LoadBalancer  # Adjust to your specific needs (e.g., NodePort)
